# シーク移動量の文字列の配列
# 例：steps = ["-300", "-60", "-10", "-5", "-1", "+1", "+5", "+10", "+60", "+300"]
steps = ["-300", "-60", "-10", "-5", "-1", "+1", "+5", "+10", "+60", "+300"]
# デレステ動画ファイルのファイルタイプ
# 例：filetype = "mp4"
filetype = "mp4"
# デレステ動画データのデコード用ハードウェアアクセラレータタイプ
# - "software"は、ハードウェア支援なしのデコード。
# - "cuda"は、CUDAを使ってデコード。
# - "vaapi"は、Intel GPUを使ってデコード。
# - "vdpau"は、NVIDIA GPUを使ってデコード。
# - "vulkan"は、各種GPUを使ってデコード。
# 例：accelerator = "cuda"
accelerator = "cuda"