name: "Unittest: Check Libs"

on:
  push:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
    - uses: actions/checkout@v6
      with:
        persist-credentials: false
    
    - name: Update Packages
      run: |
        sudo apt-get update
        sudo apt-get install ffmpeg python3-dev libavutil-dev libavformat-dev libavcodec-dev libswscale-dev

    - name: Python
      uses: actions/setup-python@v6
      with:
        python-version: "3.12"

    - name: Python Requirements
      run: |
        python -m pip install --upgrade pip
        pip install -U build

    - name: Build
      run: |
        python -m build

    - name: Unittest Libs
      run: |
        pip install .
        python -m unittest discover tests
